kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: persistent-volume-claim-nas
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
